### ISSUE TITLE
Picker is opened with empty list when incoming/outgoing calls are not available.

### ISSUE THREAD

**Issue by 231tr0n** [bassamsdata/namu.nvim#39]
Hi bassamsdata! Is it possible to not open the picker when incoming/outgoing calls are not available. Currently, when an LSP like lua_ls which does not support incoming/outgoing calls functionality is configured, toggling the namu picker for showing lsp call heirarchy related things opens a picker on top of showing a message using vim.notify.

![Image](https://github.com/user-attachments/assets/a33d95eb-4567-43ca-acdb-9cdae5eb58f5)

**Comment by bassamsdata** [comment]
Thank you.  I’ll do my best to fix it right away.

**Comment by bassamsdata** [comment]
Hey @231tr0n! I just pushed a fix for the call hierarchy. It should now work as expected by not showing Namu if the LSP doesn’t support it or if there are no results.

Thank you

**Comment by 231tr0n** [comment]
@bassamsdata apparantly the same issue persists for ``:Namu workspace`` as well.

**Comment by bassamsdata** [comment]
Hello @231tr0n,

`:Namu workspace` might open up blank at first with most LSPs, but don’t worry, just start typing, and the LSP will begin showing the symbols.

https://github.com/user-attachments/assets/a867bd04-578b-41c0-a803-2e3d4c412dbe

**Comment by bassamsdata** [comment]
> The thing is it can open up on buffers like mini.starter and it makes no sense for it to open since these wont have an lsp attached.

You’re absolutely right, I hadn’t thought of that inconvenience. Thanks for pointing it out. I’ll get it fixed.
