### ISSUE TITLE
error when binding <C-c> to close

### ISSUE THREAD

**Issue by lost22git** [bassamsdata/namu.nvim#43]
- version
```
branch main
commit dce3d5c
```

- config
```lua
{
    'bassamsdata/namu.nvim',
    cmd = { 'Namu' },
    opts = {
      namu_symbols = {
        enable = true,
        options = {
          movement = {
            next = { '<M-j>' },
            previous = { '<M-k>' },
            close = { '<C-c>', '<Esc>' },
          },
        },
      },
      ui_select = { enable = false },
    },
  }
```

- error
```
Error executing vim.schedule lua callback: ...l/share/nvim/lazy/namu.nvim/lua/namu/selecta/selecta.lua:1966: Keyboard interrupt
stack traceback:
	[C]: in function 'error'
	...l/share/nvim/lazy/namu.nvim/lua/namu/selecta/selecta.lua:1966: in function 'pick'
	...share/nvim/lazy/namu.nvim/lua/namu/core/symbol_utils.lua:723: in function 'show_picker'
	...re/nvim/lazy/namu.nvim/lua/namu/namu_symbols/symbols.lua:308: in function 'callback'
	.../share/nvim/lazy/namu.nvim/lua/namu/namu_symbols/lsp.lua:170: in function 'handler'
	...rmux/files/usr/share/nvim/runtime/lua/vim/lsp/client.lua:682: in function 'fn'
	vim/_editor.lua:366: in function <vim/_editor.lua:365>
```

**Comment by bassamsdata** [comment]
Thank you for bringing this up, @lost22git! I was able to reproduce the issue and will look into it as soon as possible.

**Comment by bassamsdata** [comment]
Hey @lost22git ! I just pushed a fix for this, so it should be working now. Let me know if you’re still running into any issues!

**Comment by lost22git** [comment]
Unfortunately, the isssue still exists.

- version
```
branch main
commit 3451272
```

- error
```
Error executing vim.schedule lua callback: ...l/share/nvim/lazy/namu.nvim/lua/namu/selecta/selecta.lua:1969: Keyboard interrupt
stack traceback:
	[C]: in function 'error'
	...l/share/nvim/lazy/namu.nvim/lua/namu/selecta/selecta.lua:1969: in function 'pick'
	...share/nvim/lazy/namu.nvim/lua/namu/core/symbol_utils.lua:723: in function 'show_picker'
	...re/nvim/lazy/namu.nvim/lua/namu/namu_symbols/symbols.lua:308: in function 'callback'
	.../share/nvim/lazy/namu.nvim/lua/namu/namu_symbols/lsp.lua:170: in function 'handler'
	...rmux/files/usr/share/nvim/runtime/lua/vim/lsp/client.lua:682: in function 'fn'
	vim/_editor.lua:366: in function <vim/_editor.lua:365>
```

**Comment by lost22git** [comment]
Unfortunately, the isssue still exists.

- version
```
branch main
commit 3451272
```

- error
```
Error executing vim.schedule lua callback: ...l/share/nvim/lazy/namu.nvim/lua/namu/selecta/selecta.lua:1969: Keyboard interrupt
stack traceback:
	[C]: in function 'error'
	...l/share/nvim/lazy/namu.nvim/lua/namu/selecta/selecta.lua:1969: in function 'pick'
	...share/nvim/lazy/namu.nvim/lua/namu/core/symbol_utils.lua:723: in function 'show_picker'
	...re/nvim/lazy/namu.nvim/lua/namu/namu_symbols/symbols.lua:308: in function 'callback'
	.../share/nvim/lazy/namu.nvim/lua/namu/namu_symbols/lsp.lua:170: in function 'handler'
	...rmux/files/usr/share/nvim/runtime/lua/vim/lsp/client.lua:682: in function 'fn'
	vim/_editor.lua:366: in function <vim/_editor.lua:365>
```

**Comment by bassamsdata** [comment]
Hey @lost22git, thanks for the heads-up! Would you mind updating the plugin and giving it another try?

**Comment by bassamsdata** [comment]
Hey @lost22git! I’m not exactly sure what’s causing the issue since it’s working fine on my end, but I suspect it might have something to do with how key codes are interpreted differently across terminals.

Would you mind letting me know which terminal you’re using? I’m currently refactoring the core of the plugin to better align with normal buffer behavior, which resolve a lot of issues, including this one. That update is already in the nightly branch and should be released in a few days.

In the meantime, I’ll give it another try and see if I can find a solution.

Thank you

**Comment by lost22git** [comment]
Tmux on Termux

**Comment by L-Colombo** [comment]
I am having the same exact issue, with the latest updated version of the plugin.
Tried on ST and alacritty, on both with Tmux and without, same outcome.

**Comment by bassamsdata** [comment]
Thank you @L-Colombo! I believe this should be resolved once the nightly branch is merged into main. I still have two small bugs to fix in that branch, and I’m hoping to get them sorted out tomorrow.

**Comment by L-Colombo** [comment]
It was perfectly as intended, tank you!
I really appreciated the help and the courtesy
